#!/usr/bin/env python3
"""Derive PowerPoint's built-in table styles by measuring its own rendering.

PowerPoint keeps the built-in table styles inside the application: a deck that uses one
records only its GUID, and ``ppt/tableStyles.xml`` holds custom styles and a default id
and nothing else.  There is no file on this machine to read the definitions out of --
they were looked for.  So this script asks PowerPoint to draw them and reads the answer
back off the pixels.

It runs in three stages:

1. **A swatch sheet** -- one slide of small rectangles, each filled with a known OOXML
   colour expression (``accent1``, ``accent1`` + ``tint 40%``, ``lt2`` + ``lumMod 60%``,
   ...).  Rendering it through PowerPoint yields an exact colour-to-expression
   dictionary, so a colour sampled later can be *named* rather than approximated.  It
   also pins down PowerPoint's own transform maths, which is how the linear-light
   tint/shade behaviour in ``resolve/color.py`` was established.

2. **A style probe** -- one slide per candidate GUID, each carrying three tables laid out
   so that every conditional region lands at a known row and column:

   =======  =======================================================================
   table A  6x5, ``firstRow``/``lastRow``/``firstCol``/``lastCol``/``bandRow``:
            exposes the header, the footer, both edge columns, horizontal banding
            and all four corner cells
   table B  4x6, ``bandCol`` only: isolates vertical banding
   table C  3x3, no flags: the whole-table style, unobstructed
   =======  =======================================================================

   The probe is exported twice, over a white slide background and over a black one.  A
   composited colour then gives two equations in two unknowns::

       observed = colour * alpha + backdrop * (1 - alpha)

   so alpha falls out instead of being guessed -- which matters, because the entire
   Light Style family bands with 20%-alpha black rather than with an opaque grey, and a
   single backdrop cannot tell those apart.  A cell that tracks the backdrop exactly has
   no fill at all.

3. **Inference** -- fills, stroke colours, stroke widths, text colours and bold are read
   per region, and only values that differ from what the lower-precedence regions
   already produce are kept, so the output is overrides and nothing else.

Two checks keep guesses out of the result.  A GUID PowerPoint does not recognise renders
exactly like "No Style, Table Grid" -- that is its fallback -- so a candidate measuring
identical to the fallback is a wrong GUID and is dropped.  And within a family the six
accent variants are generated by PowerPoint from one template, so any disagreement
between them is a measurement artefact and the minority is rewritten from the majority.

Usage (macOS, with PowerPoint installed)::

    python3 tools/derive_table_styles.py --all
    python3 tools/derive_table_styles.py --emit > body.py

Needs ``pypdfium2`` and ``pillow`` to rasterise the exports; neither is a dependency of
the library itself, which is why this lives in ``tools/`` and not in ``src/``.
"""

from __future__ import annotations

import argparse
import json
import os
import re
import subprocess
import sys
import time
import zipfile
from collections import Counter, defaultdict
from pathlib import Path

HERE = Path(__file__).resolve().parent
EXPORT_SCRIPT = HERE / "powerpoint_export_pdf.applescript"
#: PowerPoint is sandboxed and refuses paths outside the user's home with error -9074.
WORK = Path(os.path.expanduser("~/pptx2svg-table-styles"))

SLIDE_W, SLIDE_H = 9144000, 5143500
#: 2560 px across a 10 in slide is 256 dpi, which puts ~3.5 px on a 1 pt rule -- enough
#: to tell 1 pt from 2 pt from 3 pt by coverage.
WIDTH = 2560
SCALE = WIDTH / SLIDE_W
EMU_PER_POINT = 12700

BACKDROPS = ("FFFFFF", "000000")
#: Stroke widths and alphas Office actually uses; measurements are snapped to these.
WIDTHS = (1.0, 1.5, 2.0, 3.0)
ALPHAS = (0.2, 0.4, 0.5, 0.6, 0.8, 1.0)

TABLE_GRID_GUID = "{5940675A-B579-460E-94D1-54222C63F5DA}"

REGIONS = ("wholeTbl", "band1H", "band2H", "band1V", "band2V", "firstRow", "lastRow",
           "firstCol", "lastCol", "nwCell", "neCell", "swCell", "seCell")
SIDES = ("left", "right", "top", "bottom", "insideH", "insideV")

#: Colour-map slots and transforms the swatch sheet covers.
SLOTS = ("dk1", "lt1", "dk2", "lt2", "accent1", "accent2", "accent3", "accent4",
         "accent5", "accent6", "bg1", "tx1", "bg2", "tx2")
#: Preference when several expressions produce the same colour: a plain accent beats a
#: shaded one, and `dk1` beats the `tx1` that maps onto it.
SLOT_RANK = {"accent1": 0, "accent2": 0, "accent3": 0, "accent4": 0, "accent5": 0,
             "accent6": 0, "lt1": 1, "dk1": 1, "lt2": 2, "dk2": 2,
             "bg1": 3, "tx1": 3, "bg2": 4, "tx2": 4}

# The candidate GUIDs.  Ones PowerPoint does not recognise are detected and dropped, so
# this list is allowed to be wrong; it is not allowed to be trusted.
#
# Provenance of the two that arrived last, since "where did this GUID come from" is the
# question a reader will have:
#   {793D81CF-...} "Medium Style 1"          -- read out of PowerPoint's own executable,
#       which carries exactly fifteen brace-delimited GUIDs; fourteen were already here.
#       `strings "/Applications/Microsoft PowerPoint.app/Contents/MacOS/Microsoft
#       PowerPoint" | grep -oE '{[0-9A-F-]{36}}'` reproduces it.
#   {D27102A9-...} "Light Style 1 - Accent 4" -- from aiden0z/pptx-renderer's published
#       list.  Published lists are candidates, never answers; this one survived the
#       fallback check below and came out carrying accent 4 in the Light Style 1 shape.
CANDIDATES: list[tuple[str, str]] = [
    ("{2D5ABB26-0587-4C30-8999-92F81FD0307C}", "No Style, No Grid"),
    ("{5940675A-B579-460E-94D1-54222C63F5DA}", "No Style, Table Grid"),
    ("{3C2FFA5D-87B4-456A-9821-1D502468CF0F}", "Themed Style 1 - Accent 1"),
    ("{284E427A-3D55-4303-BF80-6455036E1DE7}", "Themed Style 1 - Accent 2"),
    ("{69C7853C-536D-4A76-A0AE-DD22124D55A5}", "Themed Style 1 - Accent 3"),
    ("{775DCB02-9BB8-47FD-8907-85C794F793BA}", "Themed Style 1 - Accent 4"),
    ("{35758FB7-9AC5-4552-8A53-C91805E547FA}", "Themed Style 1 - Accent 5"),
    ("{08FB837D-C827-4EFA-A057-4D05807E0F7C}", "Themed Style 1 - Accent 6"),
    ("{D113A9D2-9D6B-4929-AA2D-F23B5EE8CBE7}", "Themed Style 2 - Accent 1"),
    ("{18603FDC-E32A-4AB5-989C-0864C3EAD2B8}", "Themed Style 2 - Accent 2"),
    ("{306799F8-075E-4A3A-A7F6-7FBC6576F1A4}", "Themed Style 2 - Accent 3"),
    ("{E269D01E-BC32-4049-B463-5C60D7B0CCD2}", "Themed Style 2 - Accent 4"),
    ("{327F97BB-C833-4FB7-BDE5-3F7075034690}", "Themed Style 2 - Accent 5"),
    ("{638B1855-1B75-4FBE-930C-398BA8C253C6}", "Themed Style 2 - Accent 6"),
    ("{9D7B26C5-4107-4FEC-AEDC-1716B250A1EF}", "Light Style 1"),
    ("{3B4B98B0-60AC-42C2-AFA5-B58CD77FA1E5}", "Light Style 1 - Accent 1"),
    ("{0E3FDE45-AF77-4B5C-9715-49D594BDF05E}", "Light Style 1 - Accent 2"),
    ("{C083E6E3-FA7D-4D7B-A595-EF9225AFEA82}", "Light Style 1 - Accent 3"),
    ("{D27102A9-8310-4765-A935-A1911B00CA55}", "Light Style 1 - Accent 4"),
    ("{5FD0F851-EC5A-4D38-B0AD-8093EC10F338}", "Light Style 1 - Accent 5"),
    ("{68D230F3-CF80-4859-8CE7-A43EE81993B5}", "Light Style 1 - Accent 6"),
    ("{7E9639D4-E3E2-4D34-9284-5A2195B3D0D7}", "Light Style 2"),
    ("{69012ECD-51FC-41F1-AA8D-1B2483CD663E}", "Light Style 2 - Accent 1"),
    ("{72833802-FEF1-4C79-8D5D-14CF1EAF98D9}", "Light Style 2 - Accent 2"),
    ("{F2DE63D5-997A-4646-A377-4702673A728D}", "Light Style 2 - Accent 3"),
    ("{17292A2E-F333-43FB-9621-5CBBE7FDCDCB}", "Light Style 2 - Accent 4"),
    ("{5A111915-BE36-4E01-A7E5-04B1672EAD32}", "Light Style 2 - Accent 5"),
    ("{912C8C85-51F0-491E-9774-3900AFEF0FD7}", "Light Style 2 - Accent 6"),
    ("{616DA210-FB5B-4158-B5E0-FEB733F419BA}", "Light Style 3"),
    ("{BC89EF96-8CEA-46FF-86C4-4CE0E7609802}", "Light Style 3 - Accent 1"),
    ("{5DA37D80-6434-44D0-A028-1B22A696006F}", "Light Style 3 - Accent 2"),
    ("{8799B23B-EC83-4686-B30A-512413B5E67A}", "Light Style 3 - Accent 3"),
    ("{ED083AE6-46FA-4A59-8FB0-9F97EB10719F}", "Light Style 3 - Accent 4"),
    ("{BDBED569-4797-4DF1-A0F4-6AAB3CD982D8}", "Light Style 3 - Accent 5"),
    ("{E8B1032C-EA38-4F05-BA0D-38AFFFC7BED3}", "Light Style 3 - Accent 6"),
    ("{793D81CF-94F2-401A-BA57-92F5A7B2D0C5}", "Medium Style 1"),
    ("{B301B821-A1FF-4177-AEE7-76D212191A09}", "Medium Style 1 - Accent 1"),
    ("{9DCAF9ED-07DC-4A11-8D7F-57B35C25682E}", "Medium Style 1 - Accent 2"),
    ("{1FECB4D8-DB02-4DC6-A0A2-4F2EBAE1DC90}", "Medium Style 1 - Accent 3"),
    ("{1E171933-4619-4E11-9A3F-F7608DF75F80}", "Medium Style 1 - Accent 4"),
    ("{FABFCF23-3B69-468F-B69F-88F6DE6A72F2}", "Medium Style 1 - Accent 5"),
    ("{10A1B5D5-9B99-4C35-A422-299274C87663}", "Medium Style 1 - Accent 6"),
    ("{073A0DAA-6AF3-43AB-8588-CEC1D06C72B9}", "Medium Style 2"),
    ("{5C22544A-7EE6-4342-B048-85BDC9FD1C3A}", "Medium Style 2 - Accent 1"),
    ("{21E4AEA4-8DFA-4A89-87EB-49C32662AFE0}", "Medium Style 2 - Accent 2"),
    ("{F5AB1C69-6EDB-4FF4-983F-18BD219EF322}", "Medium Style 2 - Accent 3"),
    ("{00A15C55-8517-42AA-B614-E9B94910E393}", "Medium Style 2 - Accent 4"),
    ("{7DF18680-E054-41AD-8BC1-D1AEF772440D}", "Medium Style 2 - Accent 5"),
    ("{93296810-A885-4BE3-A3E7-6D5BEEA58F35}", "Medium Style 2 - Accent 6"),
    ("{8EC20E35-A176-4012-BC5E-935CFFF8708E}", "Medium Style 3"),
    ("{6E25E649-3F16-4E02-A733-19D2CDBF48F0}", "Medium Style 3 - Accent 1"),
    ("{85BE263C-DBD7-4A20-BB59-AAB30ACAA65A}", "Medium Style 3 - Accent 2"),
    ("{EB344D84-9AFB-497E-A393-DC336BA19D2E}", "Medium Style 3 - Accent 3"),
    ("{EB9631B5-78F2-41C9-869B-9F39066F8104}", "Medium Style 3 - Accent 4"),
    ("{74C1A8A3-306A-4EB7-A6B1-4F7E0EB9C5D6}", "Medium Style 3 - Accent 5"),
    ("{2A488322-F2BA-4B5B-9748-0D474271808F}", "Medium Style 3 - Accent 6"),
    ("{D7AC3CCA-C797-4891-BE02-D94E43425B78}", "Medium Style 4"),
    ("{69CF1AB2-1976-4502-BF36-3FF5EA218861}", "Medium Style 4 - Accent 1"),
    ("{8A107856-5554-42FB-B03E-39F5DBC370BA}", "Medium Style 4 - Accent 2"),
    ("{0505E3EF-67EA-436B-97B2-0124C06EBD24}", "Medium Style 4 - Accent 3"),
    ("{C4B1156A-380E-4F78-BDF5-A606A8083BF9}", "Medium Style 4 - Accent 4"),
    ("{22838BEF-8BB2-4498-84A7-C5851F593DF1}", "Medium Style 4 - Accent 5"),
    ("{16D9F66E-5EB9-4882-86FB-DCBF35E3C3E4}", "Medium Style 4 - Accent 6"),
    ("{E8034E78-7F5D-4C2E-B375-FC64B27BC917}", "Dark Style 1"),
    ("{125E5076-3810-47DD-B79F-674D7AD40C01}", "Dark Style 1 - Accent 1"),
    ("{37CE84F3-28C3-443E-9E96-99CF82512B78}", "Dark Style 1 - Accent 2"),
    ("{D03447BB-5D67-496B-8E87-E561075AD55C}", "Dark Style 1 - Accent 3"),
    ("{E929F9F4-4A8F-4326-A1B4-22849713DDAB}", "Dark Style 1 - Accent 4"),
    ("{8FD4443E-F989-4FC4-A0C8-D5A2AF1F390B}", "Dark Style 1 - Accent 5"),
    ("{AF606853-7671-496A-8E4F-DF71F8EC918B}", "Dark Style 1 - Accent 6"),
    ("{5202B0CA-FC54-4496-8BCA-5EF66A818D29}", "Dark Style 2"),
    ("{0660B408-B3CF-4A94-85FC-2B1E0A45F4A2}", "Dark Style 2 - Accent 1/Accent 2"),
    ("{91EBBBCC-DAD2-459C-BE2E-F6DE35CF9A28}", "Dark Style 2 - Accent 3/Accent 4"),
    ("{46F890A9-2807-4EBB-B81D-B2AA78EC7F39}", "Dark Style 2 - Accent 5/Accent 6"),
]


# --------------------------------------------------------------------------------------
# Deck construction
# --------------------------------------------------------------------------------------

EMPTY_TREE = (
    '<p:spTree><p:nvGrpSpPr><p:cNvPr id="0" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
    '<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
    '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr></p:spTree>'
)
NAMESPACES = (
    'xmlns:a="http://schemas.openxmlformats.org/drawingml/2006/main" '
    'xmlns:r="http://schemas.openxmlformats.org/officeDocument/2006/relationships" '
    'xmlns:p="http://schemas.openxmlformats.org/presentationml/2006/main"'
)
CONTENT_TYPE_SLIDE = (
    "application/vnd.openxmlformats-officedocument.presentationml.slide+xml"
)


def background(hex_rgb: str) -> str:
    return (
        f'<p:bg><p:bgPr><a:solidFill><a:srgbClr val="{hex_rgb}"/></a:solidFill>'
        "<a:effectLst/></p:bgPr></p:bg>"
    )


def slide_document(backdrop: str, body: str) -> str:
    return (
        '<?xml version="1.0" encoding="UTF-8" standalone="yes"?>\n'
        f"<p:sld {NAMESPACES}><p:cSld>"
        + background(backdrop)
        + '<p:spTree><p:nvGrpSpPr><p:cNvPr id="0" name=""/><p:cNvGrpSpPr/><p:nvPr/></p:nvGrpSpPr>'
        '<p:grpSpPr><a:xfrm><a:off x="0" y="0"/><a:ext cx="0" cy="0"/>'
        '<a:chOff x="0" y="0"/><a:chExt cx="0" cy="0"/></a:xfrm></p:grpSpPr>'
        + body
        + "</p:spTree></p:cSld>"
        "<p:clrMapOvr><a:masterClrMapping/></p:clrMapOvr></p:sld>"
    )


def blank_template(xml: str, backdrop: str) -> str:
    """Empty a layout or master so nothing shows through an unfilled table cell."""
    xml = re.sub(r"<p:spTree>.*?</p:spTree>", EMPTY_TREE, xml, flags=re.S)
    xml = re.sub(r"<p:bg>.*?</p:bg>", "", xml, flags=re.S)
    return xml.replace("<p:cSld>", "<p:cSld>" + background(backdrop), 1)


def write_deck(source: Path, target: Path, slides: list[str], backdrop: str) -> None:
    """Clone a deck, replacing its slides with the given ones."""
    zin = zipfile.ZipFile(source)
    base_rels = zin.read("ppt/slides/_rels/slide1.xml.rels")
    presentation = zin.read("ppt/presentation.xml").decode()
    pres_rels = zin.read("ppt/_rels/presentation.xml.rels").decode()
    content_types = zin.read("[Content_Types].xml").decode()

    numbers = range(1, len(slides) + 1)
    sld_ids = "".join(f'<p:sldId id="{255 + n}" r:id="rIdS{n}"/>' for n in numbers)
    presentation = re.sub(
        r"<p:sldIdLst>.*?</p:sldIdLst>",
        f"<p:sldIdLst>{sld_ids}</p:sldIdLst>",
        presentation,
        flags=re.S,
    )

    rel_type = "http://schemas.openxmlformats.org/officeDocument/2006/relationships/slide"
    pres_rels = re.sub(r'<Relationship[^>]*Type="[^"]*/slide"[^>]*/>', "", pres_rels)
    pres_rels = pres_rels.replace(
        "</Relationships>",
        "".join(
            f'<Relationship Id="rIdS{n}" Type="{rel_type}" Target="slides/slide{n}.xml"/>'
            for n in numbers
        )
        + "</Relationships>",
    )

    content_types = re.sub(
        r'<Override PartName="/ppt/slides/slide\d+\.xml"[^>]*/>', "", content_types
    )
    content_types = content_types.replace(
        "</Types>",
        "".join(
            f'<Override PartName="/ppt/slides/slide{n}.xml" ContentType="{CONTENT_TYPE_SLIDE}"/>'
            for n in numbers
        )
        + "</Types>",
    )

    target.parent.mkdir(parents=True, exist_ok=True)
    with zipfile.ZipFile(target, "w", zipfile.ZIP_DEFLATED) as zout:
        for item in zin.infolist():
            if item.filename.startswith("ppt/slides/"):
                continue
            data = zin.read(item.filename)
            if item.filename == "ppt/presentation.xml":
                data = presentation.encode()
            elif item.filename == "ppt/_rels/presentation.xml.rels":
                data = pres_rels.encode()
            elif item.filename == "[Content_Types].xml":
                data = content_types.encode()
            elif re.search(r"slide(Layouts|Masters)/slide\w+\d+\.xml$", item.filename):
                data = blank_template(data.decode(), backdrop).encode()
            zout.writestr(item.filename, data)
        for n, xml in zip(numbers, slides):
            zout.writestr(f"ppt/slides/slide{n}.xml", xml)
            zout.writestr(f"ppt/slides/_rels/slide{n}.xml.rels", base_rels)


#: "Cancel", as PowerPoint's repair dialog spells it in the localisations likely to be
#: met.  Escape does not dismiss that dialog; only a real button click does.
CANCEL_LABELS = ("Annuleren", "Cancel", "Abbrechen", "Annuler", "Cancelar", "Annulla",
                 "Avbryt", "Anuluj", "\u041e\u0442\u043c\u0435\u043d\u0430",
                 "\u30ad\u30e3\u30f3\u30bb\u30eb", "\u53d6\u6d88", "\ucde8\uc18c")

DISMISS = """
tell application "System Events"
  tell process "Microsoft PowerPoint"
    repeat with w in windows
      repeat with label in {%s}
        try
          click button label of w
          return "clicked"
        end try
      end repeat
    end repeat
    return "none"
  end tell
end tell
"""


def unwedge() -> None:
    """Clear a modal dialog, restarting PowerPoint if that does not work.

    A deck PowerPoint wants to repair puts up an app-modal dialog, and until it is
    cleared *every* export fails -- including ones for files that are perfectly fine --
    so one bad run otherwise looks like a broken environment.  The export script cannot
    clear it: it is blocked inside `open` and never regains control.
    """
    labels = ", ".join('"%s"' % label for label in CANCEL_LABELS)
    try:
        clicked = subprocess.run(
            ["osascript", "-e", DISMISS % labels],
            capture_output=True, text=True, timeout=30,
        ).stdout.strip()
    except subprocess.TimeoutExpired:
        clicked = ""
    if clicked == "clicked":
        return
    # Needs Accessibility permission; without it, restarting is the fallback.
    subprocess.run(["pkill", "-x", "Microsoft PowerPoint"], capture_output=True)
    time.sleep(3)
    subprocess.run(["open", "-g", "-a", "/Applications/Microsoft PowerPoint.app"],
                   capture_output=True)
    time.sleep(8)


def export_pdf(deck: Path, pdf: Path, attempts: int = 2) -> None:
    detail = ""
    for attempt in range(attempts):
        pdf.unlink(missing_ok=True)
        try:
            completed = subprocess.run(
                ["osascript", str(EXPORT_SCRIPT), str(deck), str(pdf)],
                capture_output=True, text=True, timeout=900,
            )
            detail = (completed.stderr or completed.stdout).strip()
        except subprocess.TimeoutExpired:
            detail = "osascript did not return"
        if pdf.exists() and pdf.stat().st_size:
            return
        print(f"  export of {deck.name} failed ({detail}); clearing PowerPoint")
        unwedge()
    raise RuntimeError(
        f"PowerPoint did not export {deck.name}: {detail}\n"
        "If this is error -9074, check for a modal dialog in PowerPoint and that "
        f"both paths are under {Path.home()}."
    )


def render(pdf: Path):
    import pypdfium2 as pdfium

    document = pdfium.PdfDocument(str(pdf))
    for index in range(len(document)):
        page = document[index]
        yield page.render(scale=WIDTH / page.get_size()[0]).to_pil().convert("RGB").load()


# --------------------------------------------------------------------------------------
# Stage 1: the swatch sheet
# --------------------------------------------------------------------------------------

SWATCH = 120000
SWATCH_COLUMNS = 40


def swatch_expressions() -> list[tuple[str, str, str]]:
    transforms = [("plain", "")]
    for value in (5, 10, 20, 25, 30, 40, 50, 60, 75, 80, 90, 95):
        transforms.append((f"tint{value}", f'<a:tint val="{value * 1000}"/>'))
        transforms.append((f"shade{value}", f'<a:shade val="{value * 1000}"/>'))
    for mod, off in ((20, 80), (40, 60), (50, 50), (60, 40), (75, 25), (50, 0), (60, 0),
                     (75, 0), (80, 0), (85, 0), (90, 0), (95, 0), (20, 0), (40, 0)):
        body = f'<a:lumMod val="{mod * 1000}"/>'
        if off:
            body += f'<a:lumOff val="{off * 1000}"/>'
        transforms.append((f"lumMod{mod}lumOff{off}", body))
    return [
        (f"{slot}:{label}", slot, body)
        for slot in SLOTS
        for label, body in transforms
    ]


def build_swatches(source: Path) -> dict[str, tuple[int, int]]:
    shapes, index = [], {}
    for i, (name, slot, body) in enumerate(swatch_expressions()):
        x = 10000 + (i % SWATCH_COLUMNS) * SWATCH
        y = 10000 + (i // SWATCH_COLUMNS) * SWATCH
        index[name] = (x + SWATCH // 2, y + SWATCH // 2)
        shapes.append(
            f'<p:sp><p:nvSpPr><p:cNvPr id="{200 + i}" name="s{i}"/><p:cNvSpPr/><p:nvPr/></p:nvSpPr>'
            f'<p:spPr><a:xfrm><a:off x="{x}" y="{y}"/><a:ext cx="{SWATCH}" cy="{SWATCH}"/></a:xfrm>'
            f'<a:prstGeom prst="rect"><a:avLst/></a:prstGeom>'
            f'<a:solidFill><a:schemeClr val="{slot}">{body}</a:schemeClr></a:solidFill>'
            f'<a:ln><a:noFill/></a:ln></p:spPr>'
            f'<p:txBody><a:bodyPr/><a:lstStyle/><a:p><a:endParaRPr/></a:p></p:txBody></p:sp>'
        )
    write_deck(source, WORK / "swatches.pptx", [slide_document("FF00FF", "".join(shapes))], "FF00FF")
    return index


def read_swatches(index: dict[str, tuple[int, int]]) -> dict[str, list[str]]:
    export_pdf(WORK / "swatches.pptx", WORK / "swatches.pdf")
    pixels = next(render(WORK / "swatches.pdf"))
    table: dict[str, list[str]] = defaultdict(list)
    for name, (emu_x, emu_y) in index.items():
        rgb = pixels[int(emu_x * SCALE), int(emu_y * SCALE)]
        table["#%02x%02x%02x" % rgb].append(name)
    for entries in table.values():
        entries.sort(key=simplicity)
    (WORK / "swatches.json").write_text(json.dumps(table, indent=1), encoding="utf-8")
    return table


def simplicity(name: str):
    slot, label = name.split(":")
    kind = 0 if label == "plain" else 1 if label.startswith(("tint", "shade")) else 2
    return (SLOT_RANK.get(slot, 9), kind, len(label))


# --------------------------------------------------------------------------------------
# Stage 2: the style probe
# --------------------------------------------------------------------------------------

#: name, x, y, column width, columns, row height, rows, `a:tblPr` flags
PROBE_TABLES = [
    ("A", 300000, 150000, 1400000, 5, 400000, 6,
     'firstRow="1" lastRow="1" firstCol="1" lastCol="1" bandRow="1"'),
    ("B", 300000, 2750000, 1100000, 6, 300000, 4, 'bandCol="1"'),
    ("C", 300000, 4100000, 800000, 3, 300000, 3, ""),
]
#: Something with plenty of vertical stems, so ink coverage separates bold from regular.
PROBE_TEXT = "HHHH"


def probe_slide(guid: str, backdrop: str) -> tuple[str, dict]:
    frames, index = [], {}
    for i, (tag, x, y, col_w, cols, row_h, rows, flags) in enumerate(PROBE_TABLES):
        cell = (
            '<a:tc><a:txBody><a:bodyPr/><a:lstStyle/>'
            '<a:p><a:pPr algn="l" marL="0" indent="0"><a:buNone/></a:pPr>'
            f'<a:r><a:rPr lang="en-US" sz="800"/><a:t>{PROBE_TEXT}</a:t></a:r></a:p>'
            '</a:txBody><a:tcPr marL="0" marR="0" marT="0" marB="0" anchor="ctr"/></a:tc>'
        )
        body = []
        for r in range(rows):
            body.append(f'<a:tr h="{row_h}">' + cell * cols + "</a:tr>")
            for c in range(cols):
                index[f"{tag}:{r}:{c}"] = {
                    "x": x + c * col_w, "y": y + r * row_h, "w": col_w, "h": row_h
                }
        frames.append(
            f'<p:graphicFrame><p:nvGraphicFramePr><p:cNvPr id="{300 + i}" name="{tag}"/>'
            '<p:cNvGraphicFramePr/><p:nvPr/></p:nvGraphicFramePr>'
            f'<p:xfrm><a:off x="{x}" y="{y}"/>'
            f'<a:ext cx="{col_w * cols}" cy="{row_h * rows}"/></p:xfrm>'
            '<a:graphic><a:graphicData uri="http://schemas.openxmlformats.org/drawingml/2006/table">'
            f'<a:tbl><a:tblPr {flags}><a:tableStyleId>{guid}</a:tableStyleId></a:tblPr>'
            + f'<a:tblGrid>{f"""<a:gridCol w="{col_w}"/>""" * cols}</a:tblGrid>'
            + "".join(body)
            + "</a:tbl></a:graphicData></a:graphic></p:graphicFrame>"
        )
    return slide_document(backdrop, "".join(frames)), index


def build_probe(source: Path) -> dict:
    index = {}
    for backdrop in BACKDROPS:
        slides = []
        for number, (guid, name) in enumerate(CANDIDATES, start=1):
            xml, cells = probe_slide(guid, backdrop)
            slides.append(xml)
            index[str(number)] = {"guid": guid, "name": name, "cells": cells}
        write_deck(source, WORK / f"probe-{backdrop}.pptx", slides, backdrop)
    (WORK / "probe-index.json").write_text(json.dumps(index), encoding="utf-8")
    return index


# --------------------------------------------------------------------------------------
# Measurement
# --------------------------------------------------------------------------------------


def distance(a, b) -> int:
    return sum(abs(int(p) - int(q)) for p, q in zip(a, b))


def snap(value, choices):
    return min(choices, key=lambda candidate: abs(candidate - value))


def match(candidates, over_white, over_black):
    """Identify a paint from the same spot rendered over white and over black.

    Dividing the black-backed sample by alpha to recover the colour amplifies its
    rounding error fivefold at 20% alpha, which is enough to turn `accent1` into
    `accent1 shade 95%`.  Searching (colour, alpha) pairs for the one that predicts both
    observations keeps the answer on the small set of expressions Office actually uses,
    and among equally good fits the plainest expression wins.
    """
    if max(abs(w - b) for w, b in zip(over_white, over_black)) > 240:
        return None, 0.0, 0  # tracks the backdrop exactly: no paint at all
    scored = []
    for rgb, name in candidates:
        for alpha in ALPHAS:
            error = 0
            for channel in range(3):
                painted = rgb[channel] * alpha
                error += abs(painted + 255 * (1 - alpha) - over_white[channel])
                error += abs(painted - over_black[channel])
            scored.append((error, name, alpha))
    floor = min(entry[0] for entry in scored)
    close = [entry for entry in scored if entry[0] <= floor + 6]
    error, name, alpha = min(close, key=lambda e: (simplicity(e[1]), e[0], -e[2]))
    return name, alpha, error


def stroke_in(run, window):
    """Index and run length of the stroke crossing a scan, or None when bare."""
    side_a, side_b = run[0], run[-1]
    inner = [
        i for i in range(window // 2, len(run) - window // 2)
        if distance(run[i], side_a) > 12 and distance(run[i], side_b) > 12
    ]
    if not inner:
        return None
    colour, occurrences = Counter(run[i] for i in inner).most_common(1)[0]
    if occurrences < 2:
        return None
    return next(i for i in inner if run[i] == colour), occurrences


def measure_edge(white, black, emu_x, emu_y, horizontal, candidates, window=16):
    """Colour, alpha and width of the stroke on one cell edge, or None.

    Width is coverage rather than a count of exactly-matching pixels: a 1 pt line lands
    on about three and a half pixels here, so its edges are always part-covered and
    counting whole pixels loses most of a point.
    """
    cx, cy = int(round(emu_x * SCALE)), int(round(emu_y * SCALE))
    run_white, run_black = [], []
    for offset in range(-window, window + 1):
        sx, sy = (cx, cy + offset) if horizontal else (cx + offset, cy)
        try:
            run_white.append(white[sx, sy])
            run_black.append(black[sx, sy])
        except IndexError:
            return None

    # A white stroke is invisible against the white backdrop and a black one against the
    # black backdrop, so the table's outer edges only show in one of the two renders.
    found = None
    for run in (run_white, run_black):
        candidate = stroke_in(run, window)
        if candidate is not None and (found is None or candidate[1] > found[1]):
            found = (*candidate, run)
    if found is None:
        return None
    centre, _, run = found

    name, alpha, error = match(candidates, run_white[centre], run_black[centre])
    if name is None:
        return None

    side_a, side_b, stroke = run[0], run[-1], run[centre]
    coverage = 0.0
    for i, rgb in enumerate(run):
        own = side_a if i < len(run) / 2 else side_b
        span = distance(stroke, own)
        if span:
            coverage += max(0.0, min(1.0, distance(rgb, own) / span))
    return {"color": name, "alpha": alpha, "error": error,
            "width_pt": coverage / (EMU_PER_POINT * SCALE)}


def sample(index: dict, swatches: dict) -> dict:
    for backdrop in BACKDROPS:
        export_pdf(WORK / f"probe-{backdrop}.pptx", WORK / f"probe-{backdrop}.pdf")
    white_pages = list(render(WORK / "probe-FFFFFF.pdf"))
    black_pages = list(render(WORK / "probe-000000.pdf"))
    candidates = [
        (tuple(int(hexv[i:i + 2], 16) for i in (1, 3, 5)), entries[0])
        for hexv, entries in swatches.items()
    ]

    measured = {}
    for slide_no in sorted(index, key=int):
        entry = index[slide_no]
        white, black = white_pages[int(slide_no) - 1], black_pages[int(slide_no) - 1]
        record = {"guid": entry["guid"], "name": entry["name"], "cells": {}, "edges": {}}

        for key, box in entry["cells"].items():
            x, y, w, h = box["x"], box["y"], box["w"], box["h"]
            # The right quarter of the cell is clean fill: the text never reaches it.
            fx = int(round((x + w * 0.85) * SCALE))
            fy = int(round((y + h * 0.5) * SCALE))
            paint = white[fx, fy]
            fill, alpha, fill_error = match(candidates, paint, black[fx, fy])

            x0, y0 = int((x + w * 0.02) * SCALE), int((y + h * 0.15) * SCALE)
            x1, y1 = int((x + w * 0.45) * SCALE), int((y + h * 0.85) * SCALE)
            ink = total = 0
            glyph = Counter()
            for sy in range(y0, y1):
                for sx in range(x0, x1):
                    rgb = white[sx, sy]
                    total += 1
                    if distance(rgb, paint) > 120:
                        ink += 1
                        glyph[rgb] += 1
            text_rgb = glyph.most_common(1)[0][0] if glyph else paint
            text, _, text_error = match(candidates, text_rgb, text_rgb)

            record["cells"][key] = {
                "fill": fill, "fill_alpha": alpha, "fill_error": fill_error,
                "text": text, "text_error": text_error,
                "ink": ink / total if total else 0.0,
            }

            for side, (ex, ey, horizontal) in {
                "top": (x + w * 0.6, y, True),
                "bottom": (x + w * 0.6, y + h, True),
                # Above the text, which is centred and would read as a stroke.
                "left": (x, y + h * 0.12, False),
                "right": (x + w, y + h * 0.12, False),
            }.items():
                record["edges"][f"{key}:{side}"] = measure_edge(
                    white, black, ex, ey, horizontal, candidates
                )

        measured[slide_no] = record
        print(f"  slide {slide_no:>2}  {entry['name']}", flush=True)

    (WORK / "measured.json").write_text(json.dumps(measured, indent=1), encoding="utf-8")
    return measured


# --------------------------------------------------------------------------------------
# Stage 3: inference
# --------------------------------------------------------------------------------------


def spec(name: str | None, alpha: float = 1.0) -> str | None:
    """A colour as `slot`, `slot/tint40`, `slot/alpha20` -- or None for no paint."""
    if name is None:
        return None
    slot, label = name.split(":")
    parts = [slot] + ([] if label == "plain" else [label])
    alpha = snap(alpha, ALPHAS)
    if alpha < 1.0:
        parts.append(f"alpha{int(round(alpha * 100))}")
    return "/".join(parts)


def edge_spec(edge) -> list | None:
    if edge is None:
        return None
    return [snap(edge["width_pt"], WIDTHS), spec(edge["color"], edge["alpha"])]


def infer(record: dict) -> dict:
    cells, edges = record["cells"], record["edges"]
    style = {"guid": record["guid"], "name": record["name"]}

    def fill(key):
        return spec(cells[key]["fill"], cells[key]["fill_alpha"])

    def text(key):
        return spec(cells[key]["text"])

    # Ink coverage scales with cell width, so bold is only judged against body cells of
    # the same table.  Table A's body carries the whole-table text style, which makes it
    # the "not bold" reference for every region A exercises.
    body = sorted(cells[f"A:{r}:{c}"]["ink"] for r in (1, 2, 3, 4) for c in (1, 2, 3))
    reference = body[len(body) // 2]

    def bold(key):
        return cells[key]["ink"] > reference * 1.15

    whole = {"fill": fill("C:1:1"), "text": text("C:1:1"), "bold": False, "borders": {
        "left": edge_spec(edges.get("C:1:0:left")),
        "right": edge_spec(edges.get("C:1:2:right")),
        "top": edge_spec(edges.get("C:0:1:top")),
        "bottom": edge_spec(edges.get("C:2:1:bottom")),
        "insideH": edge_spec(edges.get("C:1:1:top")),
        "insideV": edge_spec(edges.get("C:1:1:left")),
    }}
    style["wholeTbl"] = whole

    # Table A's body rows are 1..4, so the banding index is row - 1; table B bands by
    # column, so it is the column index.
    for key, sample_key in (("band1H", "A:1:2"), ("band2H", "A:2:2"),
                            ("band1V", "B:1:0"), ("band2V", "B:1:1")):
        value = fill(sample_key)
        style[key] = {"fill": value if value != whole["fill"] else None}

    def region(key, expected_fill, expected_text, borders, expected_bold=False):
        is_bold = bold(key)
        sampled_fill, sampled_text = fill(key), text(key)
        return {
            "fill": sampled_fill if sampled_fill != expected_fill else None,
            "text": sampled_text if sampled_text != expected_text else None,
            "bold": is_bold if is_bold != expected_bold else None,
            "borders": {k: v for k, v in borders.items() if v is not None},
        }

    def differs(sampled, baseline):
        return sampled if sampled != baseline else None

    inside_h, inside_v = whole["borders"]["insideH"], whole["borders"]["insideV"]
    style["firstRow"] = region("A:0:2", whole["fill"], whole["text"], {
        "bottom": differs(edge_spec(edges.get("A:0:2:bottom")), inside_h),
        "insideV": differs(edge_spec(edges.get("A:0:2:right")), inside_v),
    })
    style["lastRow"] = region("A:5:2", whole["fill"], whole["text"], {
        "top": differs(edge_spec(edges.get("A:5:2:top")), inside_h),
        "insideV": differs(edge_spec(edges.get("A:5:2:right")), inside_v),
    })
    # Row 2 of table A is a band2H row, so that is what the column regions override.
    under = style["band2H"]["fill"] or whole["fill"]
    style["firstCol"] = region("A:2:0", under, whole["text"], {
        "right": differs(edge_spec(edges.get("A:2:0:right")), inside_v)})
    style["lastCol"] = region("A:2:4", under, whole["text"], {
        "left": differs(edge_spec(edges.get("A:2:4:left")), inside_v)})

    # Corners inherit from the row regions, which outrank the column regions.
    for key, corner, row in (("A:0:0", "nwCell", "firstRow"), ("A:0:4", "neCell", "firstRow"),
                             ("A:5:0", "swCell", "lastRow"), ("A:5:4", "seCell", "lastRow")):
        style[corner] = region(
            key,
            style[row]["fill"] or whole["fill"],
            style[row]["text"] or whole["text"],
            {},
            expected_bold=bool(style[row]["bold"]),
        )
    return style


def signature(style: dict) -> str:
    return json.dumps({key: style[key] for key in REGIONS}, sort_keys=True)


def normalise_families(styles: dict, dropped: set) -> None:
    """Make each family's accent variants agree.

    PowerPoint generates them from one template, so a disagreement is a measurement
    artefact -- a colour match gone astray on a low-contrast accent, or a hairline seen
    in some accents and not others.  Rewriting the minority from the majority invents
    nothing: the majority definition is itself measured.
    """
    families = defaultdict(dict)
    for guid, style in styles.items():
        if guid in dropped:
            continue
        match_ = re.match(r"^(.*?) - Accent (\d)$", style["name"])
        if match_:
            families[match_.group(1)][guid] = match_.group(2)

    for family, members in families.items():
        shapes = defaultdict(list)
        for guid in members:
            shapes[re.sub(r"accent\d", "accentN", signature(styles[guid]))].append(guid)
        if len(shapes) < 2:
            continue
        template = max(shapes, key=lambda body: len(shapes[body]))
        for body, guids in shapes.items():
            if body == template:
                continue
            for guid in guids:
                styles[guid].update(
                    json.loads(template.replace("accentN", f"accent{members[guid]}"))
                )
                print(f"  normalised {styles[guid]['name']} to the {family} majority")


def emit(styles: dict) -> str:
    fallback = signature(styles[TABLE_GRID_GUID])
    dropped = {
        guid for guid, style in styles.items()
        if guid != TABLE_GRID_GUID and signature(style) == fallback
    }
    normalise_families(styles, dropped)
    for guid in sorted(dropped):
        print(f"  dropped {styles[guid]['name']}: PowerPoint does not know that GUID")

    lines = []
    for guid, style in styles.items():
        if guid in dropped:
            continue
        lines.append(f'    "{guid}": {{')
        lines.append(f'        "name": "{style["name"]}",')
        for name in REGIONS:
            region, parts = style[name], []
            for key in ("fill", "text"):
                if region.get(key):
                    parts.append(f'"{key}": "{region[key]}"')
            if region.get("bold"):
                parts.append('"bold": True')
            borders = {k: v for k, v in region.get("borders", {}).items() if v}
            if borders:
                parts.append(
                    '"borders": {'
                    + ", ".join(
                        f'"{side}": ({borders[side][0]}, "{borders[side][1]}")'
                        for side in SIDES if side in borders
                    )
                    + "}"
                )
            if parts:
                lines.append(f'        "{name}": {{' + ", ".join(parts) + "},")
        lines.append("    },")
    return "\n".join(lines) + "\n"


# --------------------------------------------------------------------------------------


def main() -> int:
    parser = argparse.ArgumentParser(description=__doc__.splitlines()[0])
    parser.add_argument(
        "--source",
        type=Path,
        default=HERE.parent / "tests/fixtures/authoring-integration.pptx",
        help="deck whose theme, layout and master the probes borrow",
    )
    parser.add_argument("--swatches", action="store_true", help="build and read the swatch sheet")
    parser.add_argument("--probe", action="store_true", help="build and measure the style probe")
    parser.add_argument("--emit", action="store_true", help="print the catalogue body")
    parser.add_argument("--all", action="store_true", help="all three stages")
    args = parser.parse_args()

    if not (args.swatches or args.probe or args.emit or args.all):
        parser.error("nothing to do: pass --all, or one of --swatches/--probe/--emit")
    if not EXPORT_SCRIPT.exists():
        parser.error(f"{EXPORT_SCRIPT} is missing")
    WORK.mkdir(parents=True, exist_ok=True)

    if args.swatches or args.all:
        print("building the swatch sheet")
        read_swatches(build_swatches(args.source))
    if args.probe or args.all:
        print("building the style probe")
        index = build_probe(args.source)
        swatches = json.loads((WORK / "swatches.json").read_text(encoding="utf-8"))
        sample(index, swatches)
    if args.emit or args.all:
        measured = json.loads((WORK / "measured.json").read_text(encoding="utf-8"))
        styles = {}
        for slide_no in sorted(measured, key=int):
            style = infer(measured[slide_no])
            styles[style["guid"]] = style
        body = emit(styles)
        print("\n# paste into BUILTIN_TABLE_STYLES in "
              "src/pptx2svg/parse/table_styles_builtin.py\n", file=sys.stderr)
        print(body)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
